package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class auction_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List<String> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE9\"> \r\n");
      out.write("    <META HTTP-EQUIV=\"pragma\" CONTENT=\"no-cache\">\r\n");
      out.write("\t<META HTTP-EQUIV=\"Cache-Control\" CONTENT=\"no-cache, must-revalidate\">\r\n");
      out.write("     <title>福建农林大学二手拍卖交易网</title>\r\n");
      out.write("\t<script type = \"text/javascript\" src = \"");
      out.print(basePath);
      out.write("/js/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("\t<script type = \"text/javascript\" src = \"");
      out.print(basePath);
      out.write("/js/ajaxfileupload.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.4.2/jquery.easyui.min.js\"></script>\r\n");
      out.write("\t<script type = \"text/javascript\" src = \"");
      out.print(basePath);
      out.write("/auction/js/auction.js\"></script>\r\n");
      out.write("\t<script type = \"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/slickfile/slick/slick.min.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(basePath);
      out.write("/slickfile/slick/slick.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.4.2/themes/default/easyui.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.4.2/themes/icon.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/js/jquery-easyui-1.4.2/demo.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/auction/css/auction.css\">\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t.tdSie{font-size: 12px;font-weight: bold;}\r\n");
      out.write("\t\t#loading-mask {position: fixed;_position: absolute;left: 0;top: 0;width:100%;height:100%;z-index: 20000;background-color:#000;filter:alpha(Opacity = 50);-moz-opacity:0.8;opacity:0.8;}\r\n");
      out.write("\t\t#loading {position: absolute;left: 50%;top: 50%;padding: 2px;z-index: 20001;height: auto;}\r\n");
      out.write("\t\t#loading-msg {font: bold 14px arial, tahoma, sans-serif ;font-weight:bolder;line-height:35px;color:#fff;}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.slick-dots { display:none; }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t/*easyui表格重新渲染*/\t\r\n");
      out.write("\t #win-all-goods .datagrid-header-row td{background-color:#D8950F;color:#fff;height:50px;text-align: center;font-size:40px;font-family: 华文琥珀;}   \r\n");
      out.write("\t #win-all-goods .datagrid-header .datagrid-cell span{font-size:25px;font-family: 华文琥珀;}   \r\n");
      out.write("\t #win-all-goods .datagrid-cell, .datagrid-cell-group, .datagrid-header-rownumber, .datagrid-cell-rownumber{line-height: 25px;}   \r\n");
      out.write("\t #win-all-goods .datagrid .datagrid-pager{background-color:#D8950F;}   \r\n");
      out.write("\t #win-all-goods .panel-body{color:white}   \r\n");
      out.write("\t #win-all-goods .pagination-info{color:white}   \r\n");
      out.write("\t #win-all-goods .datagrid-row{cursor:pointer;}   \r\n");
      out.write("\t #win-all-goods .panel-body-noheader{border: 0px;}    \r\n");
      out.write("\t #win-all-goods .panel-body{border: 0px;}   \r\n");
      out.write("\t #win-this-goods .panel-body-noheader{border: 0px;}    \r\n");
      out.write("\t #win-this-goods .panel-body{border: 0px;}   \r\n");
      out.write("\t #win-this-goods .datagrid .datagrid-pager{background-color:#D8950F;} \r\n");
      out.write("\t #win-this-goods .panel-body{color:white} \r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t//设置全局变量共ajax请求用\r\n");
      out.write("\t\tvar path = '");
      out.print(path);
      out.write("';\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t    $('.slick').slick({\r\n");
      out.write("\t\t        dots: true,\r\n");
      out.write("\t\t    accessibility:true,\r\n");
      out.write("\t\t    arrows:true,\r\n");
      out.write("\t\t    autoplay:true, \r\n");
      out.write("\t\t    fade:true,\r\n");
      out.write("\t\t    pauseOnHover:true,\r\n");
      out.write("\t\t    centerPadding:'20px'\r\n");
      out.write("\t\t   /*  slidesToShow: 1,\r\n");
      out.write("\t\t    slidesToScroll: 1 */\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t \r\n");
      out.write("\t</script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \t\r\n");
      out.write("  <body style=\"padding: 0px;margin: 0px; background-color: #A9FACD;\" class=\"easyui-layout\">\r\n");
      out.write("  <!-- <div class=\"easyui-layout\" style=\"width:1349px;height:660px;margin: 0px auto;\"> -->\r\n");
      out.write("   \t<div id=\"win-top\" data-options=\"region:'north',border:false\" style=\"height:60px;background:#A9FACD;padding:10px;background: url(");
      out.print(basePath);
      out.write("/icons/11.jpg) no-repeat;\">\r\n");
      out.write("   \t\t<div style=\"height: 20px;background-color: ;\"></div>\r\n");
      out.write("   \t\t<div id=\"win-top-bottom\" style=\"height:20px;background-color: ; text-align: right;\">\r\n");
      out.write("   \t\t\t<marquee behavior='alternate' bgcolor='' direction=\"right\" scrollamount=\"1\" style=\"width: 300px;height: 19px;font-size: 18px;\" id=\"user-info-div\">\r\n");
      out.write("\t\t\t\t     \r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t</div>\r\n");
      out.write("<!-- \t<div data-options=\"region:'south',border:false\" style=\"height:50px;background:#A9FACD;padding:10px;text-align: center;line-height: 25px;\">\r\n");
      out.write("\t\t福建农林大学二手拍卖网 版权所有\r\n");
      out.write("Copyright 2016 All Rights Reserved\r\n");
      out.write("\t</div> -->\r\n");
      out.write("\t\t<div data-options=\"region:'center',title:''\" style=\"background: url(");
      out.print(basePath);
      out.write("/icons/bg.jpg) no-repeat;\">\t\r\n");
      out.write("\t\t\t<!-- 返回主页面入口开始 -->\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<!-- 返回主页面入口结束 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 卖家入口开始 -->\r\n");
      out.write("\t\t\t<div id='sale_entry' style=\"position: absolute;margin-top: 50px;margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t<img alt=\"卖家\" src=\"");
      out.print(basePath);
      out.write("/icons/sale.png\" style=\"height: 50px;width: 50px;\" onclick=\"add()\" title='卖家入口'>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 卖家入口结束 -->\r\n");
      out.write("\t\t\t<!-- 竞拍入口开始 -->\r\n");
      out.write("\t\t\t<div id='buy_entry' style=\"position: absolute;margin-top: 50px;margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t<img alt=\"竞拍\" src=\"");
      out.print(basePath);
      out.write("/icons/buy.png\" style=\"height: 50px;width: 50px;\" onclick=\"show_buy()\" title='竞拍入口'>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 竞拍入口结束 -->\r\n");
      out.write("\t\t\t<!-- 退出开始 -->\r\n");
      out.write("\t\t\t<div id='exit_buy' style=\"position: absolute;margin-top: 150px;margin-left: 10px;height: 51px;width: 51px;\">\r\n");
      out.write("\t\t\t\t<img alt=\"返回上一级\" src=\"");
      out.print(basePath);
      out.write("/icons/back.png\" style=\"height: 50px;width: 50px;\" onclick=\"exit_buy()\" title='返回'>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 退出结束 -->\r\n");
      out.write("\t\t\t<!-- 登入开始 -->\r\n");
      out.write("\t\t\t<div id='login-btn' style=\"position: absolute;margin-top: 220px;margin-left: 10px;height: 51px;width: 51px;\">\r\n");
      out.write("\t\t\t\t<img alt=\"登入\" src=\"");
      out.print(basePath);
      out.write("/icons/login.jpg\" style=\"height: 50px;width: 50px;\" onclick=\"login_show();\" title='登入'>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 登入结束 -->\r\n");
      out.write("\t\t\t<!-- quit开始 -->\r\n");
      out.write("\t\t\t<div id='quit-btn' style=\"position: absolute;margin-top: 320px;margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t<img alt=\"注销\" src=\"");
      out.print(basePath);
      out.write("/icons/quit.jpg\" style=\"height: 50px;width: 50px;\" onclick=\"quit_btn()\" title='注销'>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- quit结束 -->\r\n");
      out.write("\t\t\t<!-- 超管登入开始 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 超管登入结束 -->\r\n");
      out.write("\t\t\t<!-- <div id='user-div' style=\"position: absolute;margin-top: 25px;margin-left: 1100px;width: 100px;height:100px;background-color: #E8F1FF;text-align: center;\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 窗体主体开始 -->\r\n");
      out.write("\t\t\t<div id=\"win-all-goods\" style=\"width:800px;margin-left:150px;float: left;margin-top: 20px;\">\r\n");
      out.write("\t\t\t\t<table id=\"goods-table\"></table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div style=\"position: absolute;height:110px;width:240px;margin-left: 1000px;margin-top:20px;float: left;\" id=\"slick-pic\">\r\n");
      out.write("\t\t\t\t<span style='font-size:20px;color:#D8950F;font-family: 幼圆;font-weight: bolder;'>图片天地</span>\r\n");
      out.write("\t\t\t\t<div class=\"slick\" style=\"text-align: center;margin-left:40px;cursor:pointer;\" title='点击图片访问'>\r\n");
      out.write("\t\t\t\t    <div><a><img class='pic' id=\"pic1\" src=\"");
      out.print(basePath);
      out.write("/icons/man.jpg\" alt=\"\" style='height:100px;width:200px;'></a></div>\r\n");
      out.write("\t\t\t\t    <div><a><img class='pic' id=\"pic2\" src=\"");
      out.print(basePath);
      out.write("/icons/man.jpg\" alt=\"\" style='height:100px;width:200px;'></a></div>\r\n");
      out.write("\t\t\t\t    <div><a><img class='pic' id=\"pic3\" src=\"");
      out.print(basePath);
      out.write("/icons/man.jpg\" alt=\"\" style='height:100px;width:200px;'></a></div>\r\n");
      out.write("\t\t\t\t    <input type ='text' id='pic11' name='pic1' value=\"\" style='display:none;'>\r\n");
      out.write("\t\t\t\t    <input type ='text' id='pic21' name='pic2' value=\"\" style='display:none;'>\r\n");
      out.write("\t\t\t\t    <input type ='text' id='pic31' name='pic3' value=\"\" style='display:none;'>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"position: absolute;height:110px;width:240px;margin-left: 1000px;margin-top:200px;float: left;background-color:transparent;\" id=\"super-message\" >\r\n");
      out.write("\t\t\t\t<span style='font-size:20px;color:#D8950F;font-family: 幼圆;font-weight: bolder;'>用户公告</span>\r\n");
      out.write("\t\t\t\t<div style='margin-left: 30px;margin-top: 10px;color:#D8950F;font-size: 15px;'>\r\n");
      out.write("\t\t\t\t\t<marquee direction=\"down\" scrollamount=\"1\" style=\"width: 200px;height: 100px;cursor: pointer;\" id=\"message-div\" title='点击查看' onmouseover=this.stop() onmouseout=this.start()>\r\n");
      out.write("\t\t\t\t     \r\n");
      out.write("\t\t\t\t \t</marquee>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 窗体主体结束 -->\r\n");
      out.write("\t\t\t<!-- 窗体 单个商品开始 -->\r\n");
      out.write("\t\t\t<div id=\"win-this-goods\" style=\"width:1000px;margin:0px auto;\">\r\n");
      out.write("\t\t\t\t<div style=\"float: left;width: 750px;\"> \r\n");
      out.write("\t\t\t\t\t<div id=\"this-goods-info\" style='width:748px;background-color: #fff;margin-top: 30px;'></div>\r\n");
      out.write("\t\t\t\t\t<div style='width:750px;' id='buyers-info-table-div'><table id=\"buyers-info-table\"></table></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div style = \"height: 300px;width: 200px;margin-top: 30px;margin-left: 790px;float: left;position: absolute;\">\r\n");
      out.write("\t\t\t\t\t<div><img alt=\"\" src=\"");
      out.print(basePath);
      out.write("/icons/user1.jpg\" style=\"width: 100px;height: 100px;margin-left:40px;margin-top:20px;\"></div>\r\n");
      out.write("\t\t\t\t\t<div id=\"salesInfo\" style='color: #D8950F;font-family:幼圆; font-size: 17px; font-weight: bolder; padding-left: 10px;'></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 窗体 单个商品结束 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- 公告弹框 -->\r\n");
      out.write("\t<div id=\"thisMessage\" class=\"easyui-dialog\" title=\"公告\" data-options=\"modal:true\" style=\"width:400px;height:200px;padding:10px\">\r\n");
      out.write("\t\t<textarea id='message-text' style='width:360px;height:140px;border: 0px;'>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</textarea>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 评论框开始  -->\r\n");
      out.write("\t<div class=\"easyui-window\" title=\"CRITIZE\" style=\"width:200px;\" id=\"critize-div\" data-options=\"resizable:false,modal:true,minimizable:false,maximizable:false,collapsible:false\">\r\n");
      out.write("\t\t<div style=\"padding:10px 10px 10px 10px\">\r\n");
      out.write("\t\t    <form  class=\"easyui-form\" method=\"post\" data-options=\"novalidate:true\">\t\r\n");
      out.write("\t\t    \t<table>\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<td class=\"tdSie\">评论：</td>\r\n");
      out.write("\t\t    \t\t\t<td><input id=\"critize-desc\" class=\"easyui-textbox\" style=\"width:100px\"></td>\r\n");
      out.write("\t\t    \t\t</tr>\r\n");
      out.write("\t\t    \t</table>\r\n");
      out.write("\t\t    </form>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    <div id=\"critize-info-div\" style=\"text-align: center;height:20px;color:red;\"></div>\r\n");
      out.write("\t\t    <div style=\"text-align:center;padding:1px\">\r\n");
      out.write("\t\t    \t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"critize()\">评论</a>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t    </div>\t\t    \r\n");
      out.write("\t</div>  \r\n");
      out.write("\t<!-- 评论框结束  -->\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- 竞拍框开始  -->\r\n");
      out.write("\t<div class=\"easyui-window\" title=\"BURER\" style=\"width:200px;\" id=\"buy-div\" data-options=\"resizable:false,modal:true,minimizable:false,maximizable:false,collapsible:false\">\r\n");
      out.write("\t\t<div style=\"padding:10px 10px 10px 10px\">\r\n");
      out.write("\t\t    <form  class=\"easyui-form\" method=\"post\" data-options=\"novalidate:true\">\t\r\n");
      out.write("\t\t    \t<table>\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<td class=\"tdSie\">竞拍价钱:</td>\r\n");
      out.write("\t\t    \t\t\t<td><input id=\"buy-price\" class=\"easyui-textbox\" style=\"width:100px\"></td>\r\n");
      out.write("\t\t    \t\t</tr>\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<td class=\"tdSie\">留言：</td>\r\n");
      out.write("\t\t    \t\t\t<td><input id=\"buy-remark\" class=\"easyui-textbox\" style=\"width:100px\"></td>\r\n");
      out.write("\t\t    \t\t</tr>\r\n");
      out.write("\t\t    \t</table>\r\n");
      out.write("\t\t    </form>\r\n");
      out.write("\t\t    <div id=\"buy-info-div\" style=\"text-align: center;height:20px;color:red;\"></div>\r\n");
      out.write("\t\t    <div style=\"text-align:center;padding:1px\">\r\n");
      out.write("\t\t    \t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"buy()\">竞拍</a>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t    </div>\t\t    \r\n");
      out.write("\t</div>  \r\n");
      out.write("\t<!-- 竞拍框结束  -->\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 登入框开始  -->\r\n");
      out.write("\t<div class=\"easyui-window\" title=\"LOGIN\" style=\"width:200px;\" id=\"login-div\" data-options=\"resizable:false,modal:true,minimizable:false,maximizable:false,collapsible:false\">\r\n");
      out.write("\t\t<div style=\"padding:10px 10px 10px 10px\">\r\n");
      out.write("\t\t    <form  class=\"easyui-form\" method=\"post\" data-options=\"novalidate:true\">\t\r\n");
      out.write("\t\t    \t<table>\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<td class=\"tdSie\">用户名:</td>\r\n");
      out.write("\t\t    \t\t\t<td><input id=\"login-user\" class=\"easyui-textbox\" data-options=\"iconCls:'icon-man'\" style=\"width:100px\"></td>\r\n");
      out.write("\t\t    \t\t</tr>\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<td class=\"tdSie\">密码：</td>\r\n");
      out.write("\t\t    \t\t\t<td><input type=\"password\" id=\"login-password\" class=\"easyui-textbox\" data-options=\"iconCls:'icon-lock'\" style=\"width:100px\"></td>\r\n");
      out.write("\t\t    \t\t</tr>\r\n");
      out.write("\t\t    \t</table>\r\n");
      out.write("\t\t    </form>\r\n");
      out.write("\t\t    <div id=\"login-info-div\" style=\"text-align: center;height:20px;color:red;\"></div>\r\n");
      out.write("\t\t    <div style=\"text-align:center;padding:1px\">\r\n");
      out.write("\t\t    \t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"login()\">登入</a>\r\n");
      out.write("\t\t    \t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"register()\">注册</a>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t    </div>\t\t    \r\n");
      out.write("\t</div>  \r\n");
      out.write("\t<!-- 登入框结束  -->\t\r\n");
      out.write("\t<!-- 注册开始  -->\r\n");
      out.write("\t<div class=\"easyui-window\" title=\"Register\" style=\"width:200px;\" id=\"register-div\" data-options=\"resizable:false,modal:true,minimizable:false,maximizable:false,collapsible:false\">\r\n");
      out.write("\t\t<div style=\"padding:10px 10px 10px 10px\">\r\n");
      out.write("\t\t    <form  class=\"easyui-form\" method=\"post\" data-options=\"novalidate:true\">\t\r\n");
      out.write("\t\t    \t<table>\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<td class=\"tdSie\">昵称：</td>\r\n");
      out.write("\t\t    \t\t\t<td><input id=\"register-nick\" class=\"easyui-textbox\" style=\"width:100px\"></td>\r\n");
      out.write("\t\t    \t\t</tr>\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<td class=\"tdSie\">用户名:</td>\r\n");
      out.write("\t\t    \t\t\t<td><input id=\"register-user\" class=\"easyui-textbox\" style=\"width:100px\"></td>\r\n");
      out.write("\t\t    \t\t</tr>\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<td class=\"tdSie\">密码：</td>\r\n");
      out.write("\t\t    \t\t\t<td><input id=\"register-password\" class=\"easyui-textbox\" style=\"width:100px\"></td>\r\n");
      out.write("\t\t    \t\t</tr>\t    \t\t\r\n");
      out.write("\t\t    \t</table>\r\n");
      out.write("\t\t    </form>\r\n");
      out.write("\t\t     <div id=\"register-info-div\" style=\"text-align: center;height:20px;color:red;\"></div>\r\n");
      out.write("\t\t    <div style=\"text-align:center;padding:1px\">\r\n");
      out.write("\t\t    \t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"resister_save()\">保存</a>\r\n");
      out.write("\t\t    \t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"login_show()\">直接登入</a>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t    </div>\t\t    \r\n");
      out.write("\t</div>  \r\n");
      out.write("\t<!-- 注册结束  -->\r\n");
      out.write("\t<!-- 新建二手物品开始  -->\r\n");
      out.write("\t<div class=\"easyui-window\" title=\"新建\" style=\"width:350px;\" id=\"add-div\" data-options=\"resizable:false,modal:true,minimizable:false,maximizable:false,collapsible:false\">\r\n");
      out.write("\t\t<div style=\"padding:10px 10px 10px 10px\">\r\n");
      out.write("\t    \t<table>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td class=\"tdSie\">商品名称:</td>\r\n");
      out.write("\t    \t\t\t<td><input id=\"add-name\" name=\"add_name\" class=\"easyui-textbox\"  style=\"width:150px\"></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td class=\"tdSie\">类别:</td>\r\n");
      out.write("\t    \t\t\t<td>\r\n");
      out.write("\t    \t\t\t\t<select id=\"add-type\" class=\"easyui-combobox\" name=\"add-type\" style=\"width:150px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"电脑\">电脑</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"服装\">服装</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t    \t\t</tr>\t\t\t   \r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td class=\"tdSie\">最低价（￥）：</td>\r\n");
      out.write("\t    \t\t\t<td><input id=\"add-min\" name=\"add_min\" class=\"easyui-textbox\" style=\"width:150px\"></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td class=\"tdSie\">商品撤柜时间：</td>\r\n");
      out.write("\t    \t\t\t<td><input id=\"add-time\" name=\"add_time\" class=\"easyui-datebox\" data-options=\"required:false,editable:false\" value=\"\" style=\"width:150px\"></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td class=\"tdSie\">商品图片（jpg）：</td>\r\n");
      out.write("\t    \t\t\t<td><input id=\"add-pic\" type=\"file\" name=\"myfiles\" style=\"width:150px\"></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td class=\"tdSie\">商品描述：</td>\r\n");
      out.write("\t    \t\t\t<td><textarea id=\"add-desc\" name=\"add_desc\" style=\"text-align:left; width: 200px; height: 100px;overflow-y:hidden;\" onkeyup=\"if(value.length>100){value=value.substr(0,100);$.messager.alert('提示','字数已经超过100字，已为你自动截取！','warning')}\"></textarea></td>\r\n");
      out.write("\t    \t\t</tr>\t\t    \t\t\r\n");
      out.write("\t    \t</table>\r\n");
      out.write("\t\t    <div id=\"add-info-div\" style=\"text-align: center;height:20px;color:red;\"></div>\r\n");
      out.write("\t\t    <div style=\"text-align:center;padding:1px\">\r\n");
      out.write("\t\t    \t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"add_save()\">寄到拍卖平台</a>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t    </div>\t\t    \r\n");
      out.write("\t</div>  \r\n");
      out.write("\t<!-- 新建二手物品结束  -->\t\r\n");
      out.write("<!-- 隐藏变量区 -->\r\n");
      out.write("<!-- 上传的图片的全路径 -->\r\n");
      out.write("<input type =\"text\" id=\"add-path\" style=\"display: none\">\r\n");
      out.write("<!-- 评论的商品所属的买主 -->\r\n");
      out.write("<input type = \"text\" style=\"display: none;\" id=\"critize_buyer\">\r\n");
      out.write("<!-- 评论的商品所属的买主的楼号 -->\r\n");
      out.write("<input type = \"text\" style=\"display: none;\" id=\"critize_buyer_identify\">\r\n");
      out.write("<!-- 进度条 -->\r\n");
      out.write("<div id='loading_shade_div' style=\"display:none;z-index: 2000;\">\r\n");
      out.write("<div id ='loading-mask'></div>\r\n");
      out.write("<div id ='loading' style='vertical-align: bottom;position:fixed;margin-bottom:50px;'>\r\n");
      out.write("<img src ='");
      out.print(basePath);
      out.write("/icons/loading.gif'  width ='50'  height ='37' style ='margin-right:8px;float:left;vertical-align:bottom;'/>\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;<span id ='loading-msg'></span>\r\n");
      out.write("</div>\r\n");
      out.write("</div> \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
